// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

    
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1bPWYZEwwMgZptP-qjlgLR2zXQCfE0PE',
    appId: '1:120899676261:web:bfb1cbfcff64102bb4fe8c',
    messagingSenderId: '120899676261',
    projectId: 'aarogy-3055d',
    authDomain: 'aarogy-3055d.firebaseapp.com',
    storageBucket: 'aarogy-3055d.firebasestorage.app',
    measurementId: 'G-RB7PYMYQFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm04dduxtAEAkQNOicDs9Vk69HcjVmo6A',
    appId: '1:120899676261:android:796d0b6dcb4778e5b4fe8c',
    messagingSenderId: '120899676261',
    projectId: 'aarogy-3055d',
    storageBucket: 'aarogy-3055d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB2FBi_49NCV--kaxa-UJZkn22YXNbsxY',
    appId: '1:120899676261:ios:11ea662f2ff4ebd4b4fe8c',
    messagingSenderId: '120899676261',
    projectId: 'aarogy-3055d',
    storageBucket: 'aarogy-3055d.firebasestorage.app',
    iosBundleId: 'com.example.aarogya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB2FBi_49NCV--kaxa-UJZkn22YXNbsxY',
    appId: '1:120899676261:ios:11ea662f2ff4ebd4b4fe8c',
    messagingSenderId: '120899676261',
    projectId: 'aarogy-3055d',
    storageBucket: 'aarogy-3055d.firebasestorage.app',
    iosBundleId: 'com.example.aarogya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1bPWYZEwwMgZptP-qjlgLR2zXQCfE0PE',
    appId: '1:120899676261:web:80697d5eabbb9c72b4fe8c',
    messagingSenderId: '120899676261',
    projectId: 'aarogy-3055d',
    authDomain: 'aarogy-3055d.firebaseapp.com',
    storageBucket: 'aarogy-3055d.firebasestorage.app',
    measurementId: 'G-GPX97HBMPX',
  );

}